/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "tertiary-fixed": "#ffdbca",
                "error-container": "#ffdad6",
                "on-tertiary-fixed": "#341100",
                "surface-container-high": "#e6e8ea",
                "primary-container": "#003366",
                "on-secondary": "#ffffff",
                "surface": "#f7f9fb",
                "surface-container-highest": "#e0e3e5",
                "surface-container-low": "#f2f4f6",
                "on-primary-fixed": "#001b3c",
                "inverse-primary": "#a7c8ff",
                "secondary-fixed-dim": "#bdc7d8",
                "on-primary-fixed-variant": "#1f477b",
                "on-tertiary-container": "#d8885c",
                "on-secondary-fixed-variant": "#3e4755",
                "surface-bright": "#f7f9fb",
                "surface-dim": "#d8dadc",
                "on-error-container": "#93000a",
                "surface-container": "#eceef0",
                "on-primary-container": "#799dd6",
                "on-tertiary": "#ffffff",
                "on-surface": "#191c1e",
                "secondary-fixed": "#d9e3f4",
                "inverse-on-surface": "#eff1f3",
                "outline": "#737780",
                "surface-variant": "#e0e3e5",
                "on-secondary-container": "#596372",
                "primary-fixed": "#d5e3ff",
                "outline-variant": "#c3c6d1",
                "surface-tint": "#3a5f94",
                "secondary-container": "#d6e0f1",
                "tertiary-container": "#592300",
                "background": "#f7f9fb",
                "on-primary": "#ffffff",
                "primary": "#003366",
                "on-error": "#ffffff",
                "tertiary-fixed-dim": "#ffb690",
                "on-secondary-fixed": "#121c28",
                "error": "#ba1a1a",
                "on-surface-variant": "#43474f",
                "surface-container-lowest": "#ffffff",
                "inverse-surface": "#2d3133",
                "primary-fixed-dim": "#a7c8ff",
                "on-tertiary-fixed-variant": "#723610",
                "secondary": "#555f6d",
                "on-background": "#191c1e",
                "tertiary": "#381300"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "manrope": ["Manrope", "sans-serif"]
            }
        },
    },
    plugins: [],
}
